Repository ProdigyErrorCodes/ProdigyErrorCodes, pull requests merged in 2022-01, with the labels that each got.

#1 Update ! LIST.md
  ! LIST.md
Labels: New error code, Completed

#3 Happens with the Dashboard too!
  ! LIST.md
Labels: New error code or trigger, Completed

#7 fix date and add another error
  ! LIST.md
Labels: Completed

#9 grammar
  README.md
Labels: Completed, Official

#10 Link to the file
  CONTRIBUTING.md
Labels: Completed, Official

#12 not sure i'm supposed to edit this
  LICENSE
Labels: Completed, Official

#13 Update ! LIST.md
  ! LIST.md
Labels: New error code or trigger, Completed, Official

#16 this is important
  ! LIST.md
Labels: Completed
